twig:
    default_path: '%kernel.project_dir%/templates'
    #    passing values to every twig template
    #    using global parameters from services.yaml
    globals:
        message: '%hello_message%'
    #    option for bootstrapping forms
    form_themes: ['bootstrap_4_layout.html.twig']
